# hwdec=d3d11va
hwdec-codecs=all
sub-auto=fuzzy
audio-file-auto=fuzzy
profile=gpu-hq
log-file="/tmp/mpv.log"
volume=30
# geometry=2560x1440
# keep-open=yes
# save-position-on-quit=yes
# icc-profile-auto
# icc-cache-dir="~~/icc_cache"
gpu-shader-cache-dir="~/.cache/mpv_shaders_cache"
# screenshot-directory="~/desktop/"
