[bell]
animation = "EaseOutExpo"
color = "0xFF0000"
duration = 0

[colors.bright]
black = "#B4B4A6"
blue = "#85ADD6"
cyan = "#82C4C4"
green = "#ACD1A8"
magenta = "#D8B6D8"
red = "#F97B58"
white = "#FAFAFA"
yellow = "#FAC761"

[colors.normal]
black = "#1E1E1E"
blue = "#6699CC"
cyan = "#5FB4B4"
green = "#99C794"
magenta = "#C695C6"
red = "#EC5F66"
white = "#F7F7F7"
yellow = "#F9AE58"

[colors.primary]
background = "#343d46"
foreground = "#D8DEE9"

[cursor]
vi_mode_style = "None"

[font]
size = 16

[font.bold]
family = "NotoMono NFM"

[font.italic]
family = "NotoMono NFM"

[font.normal]
family = "NotoMono NFM"
style = "Regular"

[general]
live_config_reload = true

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Control|Shift"

[scrolling]
history = 15000
multiplier = 5

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"'()[]{}<>"

[window]
decorations = "None"
dynamic_padding = true
dynamic_title = true
opacity = 0.98
startup_mode = "Maximized"

[window.dimensions]
columns = 0
lines = 0

[window.padding]
x = 0
y = 0
